In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.item()


7

In [ ]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape


torch.Size([2])

In [ ]:
#matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim


2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX[0]


tensor([7, 8])

In [ ]:
MATRIX.shape


torch.Size([2, 2])

In [ ]:
#tensor
TENSOR = torch.tensor([[[[3, 5, 4],
                        [2, 6, 9],
                        [2, 5, 5,],
                         [1, 7, 2]]]])

TENSOR

tensor([[[[3, 5, 4],
          [2, 6, 9],
          [2, 5, 5],
          [1, 7, 2]]]])

In [ ]:
TENSOR.ndim


4

In [ ]:
TENSOR.shape


torch.Size([1, 1, 4, 3])

In [ ]:
TENSOR = torch.tensor([[1, 2 , 4], [2 , 7, 3 ]])
TENSOR


tensor([[1, 2, 4],
        [2, 7, 3]])

In [ ]:
TENSOR.ndim


2

In [ ]:
TENSOR.shape


torch.Size([2, 3])

In [ ]:
TENSOR = torch.tensor([[[2, 3],
                      [4, 2],
                      [1, 3]]])
TENSOR

tensor([[[2, 3],
         [4, 2],
         [1, 3]]])

In [ ]:
TENSOR.ndim


3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 2])

In [ ]:
TENSOR[0]

tensor([[2, 3],
        [4, 2],
        [1, 3]])

In [ ]:
#CRIAR UM TENSOR ALEATORIO DE TAMANHO [3, 4]
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4489, 0.3507, 0.1621, 0.8329],
        [0.6349, 0.5681, 0.2667, 0.6680],
        [0.2988, 0.9877, 0.4816, 0.1555]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape


torch.Size([3, 4])

In [ ]:
  random_tensor = torch.rand(1, 3, 4)
  random_tensor

tensor([[[0.4627, 0.1646, 0.6054, 0.1912],
         [0.8216, 0.8846, 0.3625, 0.3571],
         [0.8210, 0.3487, 0.5792, 0.2125]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
random_tensor = torch.rand(1, 3, 4, 5)
random_tensor

tensor([[[[0.5780, 0.7931, 0.1201, 0.4867, 0.7470],
          [0.0360, 0.5416, 0.3281, 0.0803, 0.6377],
          [0.6579, 0.3156, 0.8896, 0.2057, 0.5369],
          [0.7639, 0.6379, 0.6498, 0.6212, 0.2165]],

         [[0.4342, 0.9590, 0.7346, 0.7852, 0.7120],
          [0.4262, 0.6150, 0.5721, 0.7572, 0.0789],
          [0.9702, 0.6370, 0.0385, 0.4195, 0.4991],
          [0.4438, 0.1076, 0.6656, 0.3608, 0.8289]],

         [[0.4657, 0.7941, 0.9034, 0.0156, 0.4896],
          [0.3931, 0.4505, 0.0737, 0.2196, 0.2960],
          [0.7680, 0.6665, 0.6662, 0.1129, 0.0264],
          [0.7184, 0.8661, 0.8386, 0.7157, 0.8659]]]])

In [ ]:
random_tensor.ndim

4

In [ ]:
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.2666, 0.6903, 0.7852, 0.8706],
         [0.1185, 0.3936, 0.9317, 0.6421],
         [0.1632, 0.3369, 0.2933, 0.1843]],

        [[0.3568, 0.8810, 0.4516, 0.2677],
         [0.2543, 0.6681, 0.6137, 0.9497],
         [0.1217, 0.0828, 0.4033, 0.5544]]])

In [ ]:
#criar um tensor aleatorio com shape similar a um tensor de imagem
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
random_image_size_tensor = torch.rand(size=(4, 297, 297)) #colour channels (R, B, P, G), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([4, 297, 297]), 3)

In [ ]:
#criar um tensor só de zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
 #criar um tensor só de 1
 ones = torch.ones(size=(3,4))
 ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
### creating a range of tensors and tensors-like



In [ ]:
# usando torch.range()

In [ ]:
torch.range(0, 10)

/tmp/ipython-input-4-86072357.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
nde77em77 = torch.arange(start=0, end=1000, step=77)
nde77em77

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
#tensors-like


In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#tensors datatypes
#float 32 tensor
#quandodtype=none, vai ser sempre float 32!
#usardtype=torch.float16 por exemplo para outro float

In [ ]:
float_32_tensor= torch.tensor([3.0, 6.0, 9.0],
                              dtype=None)
float_32_tensor


tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_32_tensor= torch.tensor([3.0, 6.0, 9.0],
                              dtype=None, #what datatype is the tensor (e.g, float32 or float16)
                              device=None, #what device is ur tensor on
                              requires_grad=False) #whether or not to track gradients with this tensors operations
float_32_tensor


tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor


tensor([ 9., 36., 81.])

In [ ]:
#getting information from tensors
#Tensors not right datatype  - to do get datatype from a tensor, can use "tensor.dtype"
#tensors not right shape = to get shape from a tensor can use "tensor.shape"
#tensors not on the right device - to get device from a tensor , can use "tensor.device"

In [ ]:
#create a tensor
some_tensor= torch.rand(3, 4)
some_tensor

tensor([[0.4340, 0.3566, 0.9742, 0.5455],
        [0.0400, 0.6512, 0.2431, 0.8825],
        [0.9976, 0.5324, 0.9673, 0.5874]])

In [ ]:
#find out details about some  tensor
print(some_tensor)
print(f"O datatype do tensor é: {some_tensor.dtype}")
print(f"O shape do tensor é: {some_tensor.shape}")
print(f"O device do tensor é: {some_tensor.device}")



tensor([[0.4340, 0.3566, 0.9742, 0.5455],
        [0.0400, 0.6512, 0.2431, 0.8825],
        [0.9976, 0.5324, 0.9673, 0.5874]])
O datatype do tensor é: torch.float32
O shape do tensor é: torch.Size([3, 4])
O device do tensor é: cpu


some_tensor.size = função
some_tensor.shape = sem ser função
^^^^^^^^^^
sao a mesma coisa!

In [ ]:
#manipulating tensors (tensor operations)
Adição
subtração
multiplicação
divisão
multiplicação de matrizes



In [ ]:
#creating a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
#multiplicação por 10, por exemplo
tensor = torch.tensor([1, 2, 3])
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor
#note que ainda se mantem como 1, 2, 3... mesmo com a multiplicação por 10..


tensor([1, 2, 3])

In [ ]:
#multiplicação por 10, por exemplo
tensor = torch.tensor([1, 2, 3])
tensor = tensor * 10
tensor

tensor([10, 20, 30])

note que aqui o tensor ja fica igual....

In [ ]:
#subtração
tensor - 10


tensor([ 0, 10, 20])

In [ ]:
tensor

tensor([10, 20, 30])

In [ ]:
#element wise multiplication
print(f"É igual a: {tensor * tensor}")


É igual a: tensor([100, 400, 900])


In [ ]:
#Matrix Multiplication
torch.matmul(tensor, tensor)


tensor(1400)

é a  soma dos resultados.... 100 + 400 + 900 = 1400

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)


tensor(1400)
CPU times: user 1.12 ms, sys: 1.12 ms, total: 2.25 ms
Wall time: 1.96 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)


CPU times: user 393 µs, sys: 24 µs, total: 417 µs
Wall time: 340 µs


tensor(1400)

matrix multiplication
(3,2) @ (3, 2) nao funciona
(3, 2) @ (2, 3) funciona
(2 ,3) @ (3, 2) funciona  

In [ ]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.1915, 0.1545, 0.2382],
        [0.5203, 0.4220, 0.6556],
        [0.4518, 0.3722, 0.5898]])

In [ ]:
torch.matmul(torch.rand(10,10), torch.rand(7,10))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (10x10 and 7x10)

o primeiro e o terceiro precisam ser iguais para ocorrer a multiplicação


In [ ]:
#shape errors
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])
torch.mm(tensor_A, tensor_B)      #-----> torch.mm == torch.matmul




RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape


(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
#'transpose' method
#.T

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
#the matrix multiplication operation works when tensor_B is transposed
print(f"O shape original é: Tensor_A = {tensor_A.shape}, Tensor_B = {tensor_B.shape}")
print(f"O shape novo é: Tensor_A= {tensor_A.shape}, Tensor_B.T= {tensor_B.T.shape}")
print(f"Multiplicando: {tensor_A.shape} @ {tensor_B.T.shape} as dimensões internas devem corresponder")
print("Output:/n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"Noutput shape/: {output.shape}")


O shape original é: Tensor_A = torch.Size([3, 2]), Tensor_B = torch.Size([3, 2])
O shape novo é: Tensor_A= torch.Size([3, 2]), Tensor_B.T= torch.Size([2, 3])
Multiplicando: torch.Size([3, 2]) @ torch.Size([2, 3]) as dimensões internas devem corresponder
Output:/n
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
Noutput shape/: torch.Size([3, 3])


In [ ]:
#find the min, maxm, mean, sum, etc (tensor aggregation)


In [ ]:
#create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
#find the min
torch.min(x), x.min()


(tensor(0), tensor(0))

In [ ]:
#find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
#find the mean | requer o tensor de float 32 para funcionar
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
#find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
#find the position  in tensor that has minimum value with argmin()
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [ ]:
#find the position in tensor that has max value with argmax()
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

In [ ]:
#reshaping, stacking, squeezing and unsqueezing tensors


reshaping - reshapes input tensor to a defined shape
view
sstacking - combine multi tensor

In [ ]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#add an extra dimension | ordem é a mesma, so muda o formato
x_reshaped = x.reshape(1, 9)
x_reshaped


tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
#change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#changing z changes x

z[: 0] = 5
z, x

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#Stack tensors on top each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
#torch.squeeze() - remove all single dimensions from a target tensor
x_reshaped
print(f"Previous tensor:{x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")
#remove extra dimensions from x_reshaped
print(f"\nNew tensor: {x_reshaped.squeeze()}")
print(f"New shape: {x_reshaped.squeeze().shape}")

Previous tensor:tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_reshaped.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
#torch.unsqueeze() - adds a single dimensions to a target tensor at a specific dimension
print(f"Previous target: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")
#add an extra dimension with unsqueeze
x_unsqueezed = x_reshaped.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")



Previous target: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]])
New shape: torch.Size([1, 1, 9])


In [ ]:
#torch.permute() -rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224,3)) # [height, width, colour_channels]

#permute the original tensor to rearrange the axis or dimension ordem
x_permuted = x_original.permute(2, 0, 1) #shifts axis 0 --> 1, 1 --> 2, 2 --> 0
print(f"Pevious shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")


Pevious shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]    #*


(tensor(728218.), tensor(728218.))

In [ ]:
#create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#let´s index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#lets index on our middle bracket (dim=1) x[0] [0] == x[0, 0]
x[0][2] [2]
  # [0] "a caixa"
  # [2] terceira linha
  # [2] terceiro numero = 9

tensor(9)

In [ ]:
# you can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
#get all values of the 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
#get all values of the 0th but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]


tensor([5])

In [ ]:
#get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
#index on x to return 9
print(x[0] [2] [2])

#index on x to return 3, 6, 9
print(x[:, :, 2])


tensor(9)
tensor([[3, 6, 9]])


In [ ]:
#Pytorch tensors &  NumPy
#NumPy --> Python numerical computing library
#*Data in NumPy, want  in PyTorch tensor --> torch.numpy(ndarray)
# PyTorch tensor --> NumPy : torch.tensor.numpy()


In [ ]:
#NumPy to tensor ]
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise

array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor.dtype

torch.float64

In [ ]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#Reprodutibility (trying to take random out of random)
#In short how a neural network learns:

#start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...

#To reduce the randomness in neural networks and PyTorch comes the concept of a *random seed*.
#Essentially what the *random seed* does is "flavour" the randomness.

In [ ]:
torch.rand(3, 3)

tensor([[0.3309, 0.5421, 0.6780],
        [0.0696, 0.7195, 0.8780],
        [0.2807, 0.6921, 0.5017]])

In [ ]:
import torch
#create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.5455, 0.5745, 0.2622, 0.5181],
        [0.4768, 0.1901, 0.7631, 0.7855],
        [0.8547, 0.5948, 0.3514, 0.4755]])
tensor([[0.6703, 0.5479, 0.9658, 0.6078],
        [0.9164, 0.4136, 0.7846, 0.9956],
        [0.8363, 0.6309, 0.1213, 0.1955]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#Let's make some random but reproducible tensors
import torch

#Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
#Running tensors and PyTorch objects on the GPUS

In [ ]:
#check for gpu access with PyTorch
import torch
torch.cuda.is_available()


True

In [ ]:
#setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#Count number of devices
torch.cuda.device_count()


1

In [ ]:
#putting tensors (and models) on the gpu


In [ ]:
#create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

#tensor not on gpu
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
#move tensor to gpu (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
#if tensor is on gpu, can't transform it to NumPy --> "numpy organiza mais rapido"
tensor_on_gpu.numpy()


TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.